return function(ctx)
    ctx
    :with("wool:red")
    :cube(10,1,1)
    :with("wool:blue")
    :rotate(0,90,0)
    :cube(10,1,1)
    :with("wool:green")
    :rotate(0,90,0)
    :cube(10,1,1)
    :with("wool:yellow")
    :rotate(0,90,0)
    :cube(10,1,1)
    :translate(10,0,0)
    :with("moreblocks:slope_stone")
    :slope({ x=1, y=1, z=0 })
    :set_node()
end